python train.py \
    --data table_det \
    --model_path /workspace/models/YOLO11/yolo11l-seg.pt \
    --epoch 60 \
    --image-size 640 \
    --close_mosaic 10 \
    --reg_max 16 \
    --batch-size 128 \
    --project table_det_yolo11l_seg_reg16 \
    --plot 1 \
    --device "0,1,2,3,4,5,6,7"